import pandas as pd
import matplotlib.pylab as plt

dalin1x = pd.read_csv('Ldalin6.csv')
dalin1y = dalin1x.pop('Data')
dalin2x = pd.read_csv('Lhegu6.csv')
dalin2y = dalin2x.pop('Data')
dalin3x = pd.read_csv('Lshenmen6.csv')
dalin3y = dalin3x.pop('Data')

hegu1x = pd.read_csv('Ltaiyuan6.csv')
hegu1y = hegu1x.pop('Data')
hegu2x = pd.read_csv('Lwangu6.csv')
hegu2y = hegu2x.pop('Data')
hegu3x = pd.read_csv('Lyangchi6.csv')
hegu3y = hegu3x.pop('Data')

shenmen1x = pd.read_csv('Lshenmen1.csv')
shenmen1y = shenmen1x.pop('Data')
shenmen2x = pd.read_csv('Lshenmen2.csv')
shenmen2y = shenmen2x.pop('Data')
shenmen3x = pd.read_csv('Lshenmen3.csv')
shenmen3y = shenmen3x.pop('Data')
plt.ylim([0,1200000])
plt.scatter(dalin1x, dalin1y,s=1, label='Dalin')
plt.scatter(dalin2x, dalin2y,s=1, label='Hegu')
plt.scatter(dalin3x, dalin3y,s=1, label='Shenmen')
plt.scatter(hegu1x,hegu1y,s=1, label='Taiyuan')
plt.scatter(hegu2x,hegu2y,s=1, label='Wangu')
plt.scatter(hegu3x,hegu3y,s=1, label='Yangchi')
plt.legend()
plt.savefig('Person_6.png')
#plt.scatter(dalin1x, dalin1y,s=1, color='g')
#plt.scatter(dalin2x, dalin2y,s=1, color='g')
#plt.scatter(dalin3x, dalin3y,s=1, color='g')
#plt.scatter(hegu1x, hegu1y,s=1, color='r')
#plt.scatter(hegu2x, hegu2y,s=1, color='r')
#plt.scatter(hegu3x, hegu3y,s=1, color='r')
#plt.scatter(shenmen1x,shenmen1y,s=1,color='b')
#plt.scatter(shenmen2x,shenmen2y,s=1,color='b')
#plt.scatter(shenmen3x,shenmen3y,s=1,color='b')
plt.show()